{% set name = "geometamaker" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geometamaker-{{ version }}.tar.gz
  sha256: 253bcdf9c29bfa725bfe6929c37d4e47533fc7a535cda37a168c005689112857

build:
  entry_points:
    - geometamaker = geometamaker.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - click
    - fsspec
    - GDAL
    - frictionless
    - numpy
    - platformdirs
    - Pydantic
    - pygeoprocessing >=2.4.5
    - pyyaml
    - requests

test:
  imports:
    - geometamaker
  commands:
    - pip check
    - geometamaker --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/natcap/geometamaker
  summary: metadata creation for geospatial data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - davemfish
